<div class="container">
	<div class="content">
		<div id="auth">
			<h1 class="title-auth">Criar Conta</h1>

			<div class="icon-auth-social">
				<div class="auth-item">
					<i class="fab fa-facebook-f icon-social"></i>
				</div>
				<div class="auth-item">
					<i class="fab fa-google icon-social"></i>
				</div>
			</div>

			<h2 class="msg-other-auth">ou use seu email para criar uma conta</h2>

			<form action="" id="formAuth">
				<div class="form-group col-12 col-lg-6">
					<div class="input-group">
						<div class="input-group-icon">
							<i class="far fa-user input-icon"></i>
						</div>
						<input type="text" class="input-auth" placeholder="Nome" aria-label="nome" aria-describedby="nome para cadastro">
					</div>
				</div>

				<div class="form-group col-12 col-lg-6">
					<div class="input-group">
						<div class="input-group-icon">
							<i class="far fa-envelope input-icon"></i>
						</div>
						<input type="email" class="input-auth" placeholder="Email" aria-label="Email" aria-describedby="email para cadastro">
					</div>
				</div>

				<div class="form-group col-12 col-lg-6">
					<div class="input-group">
						<div class="input-group-icon">
							<i class="fas fa-unlock input-icon"></i>
						</div>
						<input type="password" class="input-auth" placeholder="Senha" aria-label="senha" aria-describedby="senha para cadastro">
					</div>
				</div>

				<div class="form-group col-12 col-lg-6">
					<div class="input-group">
						<div class="input-group-icon">
							<i class="fas fa-lock input-icon"></i>
						</div>
						<input type="password" class="input-auth" placeholder="Confirmar senha" aria-label="confirmar senha" aria-describedby="confirmar senha para cadastro">
					</div>
				</div>

				<button class="btn" id="btn-auth">Cadastrar</button>
			</form>

			<p class="auth-other">Já tem uma conta? <a href="/login" class="other-link">faça login</a></p>
		</div>
	</div>
</div>