<div class="container">
	<div class="content">
		<main id="auth">
			<h1 class="title-auth">Criar Conta</h1>

			<div class="icon-auth-social">
				<button type="button" class="auth-item" tabindex="1">
					<i class="fab fa-facebook-f icon-social" title="Fazer cadastro pela sua conta do facebook" aria-label="iconFacebook"></i>
					<span class="sr-only" id="iconFacebook">Ícone para fazer cadastro pela sua conta do facebook</span>
				</button>
				<button type="button" class="auth-item" tabindex="2">
					<i class="fab fa-google icon-social" title="Fazer cadastro pela sua conta do google" aria-label="iconGoogle"></i>
					<span class="sr-only" id="iconGoogle">Ícone para fazer cadastro pela sua conta do google</span>
				</button>
			</div>

			<h3 class="msg-other-auth">ou use seu email para criar uma conta</h3>

			<form action="/cadastrar-usuario" method="POST" id="formAuth">
				<div class="form-group col-12 col-lg-6">
					<div class="input-group">
						<label class="input-group-icon" for="nome">
							<i class="far fa-user input-icon" title="Ícone do usuário" aria-label="iconUserName"></i>
							<span class="sr-only" id="iconUserName">Ícone do usuário para inserção do nome e sobrenome</span>
						</label>
						<input type="text" class="input-auth" id="nome" name="nome" placeholder="Nome e sobrenome"tabindex="3" required>
					</div>
				</div>

				<div class="form-group col-12 col-lg-6">
					<div class="input-group">
						<label class="input-group-icon" for="email">
							<i class="far fa-envelope input-icon" title="Ícone de email" aria-label="iconUserEmail"></i>
							<span class="sr-only" id="iconUserEmail">Ícone de uma envelope para inserção do email</span>
						</label>
						<input type="email" class="input-auth" id="email" name="email" placeholder="Email" tabindex="4" required>
					</div>
				</div>

				<div class="form-group col-12 col-lg-6">
					<div class="input-group">
						<label class="input-group-icon" for="senha">
							<i class="fas fa-unlock input-icon" title="Ícone de um cadeado aberto" aria-label=iconUserSenha></i>
							<span class="sr-only" id="iconUserSenha">Ícone de um cadeado para a inserção da senha</span>
						</label>
						<input type="password" class="input-auth" id="senha" name="senha" placeholder="Senha" tabindex="5" required>
					</div>
				</div>

				<div class="form-group col-12 col-lg-6">
					<div class="input-group">
						<label class="input-group-icon" for="confirmSenha">
							<i class="fas fa-lock input-icon" title="Ícone de um cadeado fechado" aria-label="iconUserConfirmSenha"></i>
							<span class="sr-only" id="iconUserConfirmSenha">Ícone de um cadeado fechado para a confirmação da senha</span>
						</label>
						<input type="password" class="input-auth" id="confirmSenha" name="confirmSenha" placeholder="Confirmar senha" tabindex="6" required>
					</div>
				</div>

				<div class="form-group form-check col-12 col-lg-8 mt-4">
					<div>
						<input type="checkbox" class="form-check-input" id="confirmTerms" tabindex="7" required>
						<label class="form-check-label" for="confirmTerms">
							Ao marcar, você confirma que leu e concorda com os
							<a href="/termos-de-uso" target="_blank" title="Leia os termos de uso" tabindex="10">termos de uso</a>
							e os
							<a href="/termos-de-privacidade" target="_blank" title="Leia os termos de privacidade" tabindex="11">termos de privacidade</a>.
						</label>
					</div>
				</div>

				<button class="btn mt-0" id="btn-auth" type="submit" title="Cadastrar usuário" tabindex="8">Cadastrar</button>
			</form>

			<p class="auth-other">Já tem uma conta? <a href="/login" title="Faça login em sua conta" class="other-link" tabindex="9">faça login</a></p>
		</main>
	</div>
</div>