<div class="container">
	<div class="content">
		<main id="forgotPassword" class="box col-md-6">
			<h1 class="title-forgot-password">Recuperação de conta</h1>

			<?php road(2); ?>

			<div class="desc-state">
				<h3 class="text-state">Você receberá um código no email <i><?= $this->view->email; ?></i></h3>
			</div>

			<div class="buttons">
				<button class="next btn order-2" type="submit" tabindex="2" id="sendConfirmMail">OK</button>
				<a href="/forgot-password" class="previou btn order-1" type="button" tabindex="3">Voltar</a>
			</div>
		</main>
	</div>
</div>