<script type="text/javascript">
	function sendForm() {
		$('#formSendCode').submit();
	}
</script>

<div class="container">
	<div class="content">
		<main id="forgotPassword" class="box col-md-7">
			<h1 class="title-forgot-password">Recuperação de conta</h1>

			<?php
				road(2);

				$codePassword = isset($_SESSION['forgotPasswordCode']['codePassword']);

				if ($codePassword) {
			?>
				<form action="/validCode" method="POST" id="formSendCode">
					<div class="content-forgot">
						<div class="desc-state">
							<h3 class="text-state">Foi enviado o código para o email <i><?= $this->view->email; ?></i></h3>
						</div>

						<div id="content-inputs-code" class="container-fluid">
							<div class="row">
								<div class="code-complete col-12 d-flex justify-content-center align-center">
									<div class="form-group">
										<label for="code">Código</label>
										<input type="tel" class="input-code-complete form-control" id="code" name="code" placeholder="Digite o código aqui" tabindex="1">
									</div>
								</div>
							</div>
						</div>

						<div class="buttons">
							<button class="next btn order-2 g-recaptcha" type="submit" tabindex="7" id="verificarCode" data-callback="sendForm" data-sitekey="<?= RECAPTCHA_GOOGLE['key'] ?>">Verificar Código</button>
							<a href="/forgot-password" class="previou btn order-1" type="button" tabindex="8">Voltar</a>
						</div>
					</div>

				</form>
			<?php } else { ?>
				<div class="content-forgot">
					<div class="desc-state">
						<h3 class="text-state">Você receberá um código no email <i><?= $this->view->email; ?></i></h3>
					</div>
				</div>

				<div class="buttons">
						<button class="next btn order-2" type="submit" tabindex="2" id="sendConfirmMail">OK</button>
						<a href="/forgot-password" class="previou btn order-1" type="button" tabindex="3">Voltar</a>
					</div>
			<?php } ?>
		</main>
	</div>
</div>