<div class="container">
	<div class="content">
		<main id="forgotPassword" class="box col-md-6">
			<h1 class="title-forgot-password">Recuperação de conta</h1>

			<?php road(); ?>

			<div class="desc-state">
				<h3>1. Digite seu email para que possamos ajudá-lo a recuperar sua conta.</h3>
			</div>

			<form action="/forgot-password-code" method="POST" class="form-row formController" id="formForgotPassword">
				<div class="content-form">
					<div class="form-group">
						<div class="form_div">
							<input type="email" name="email" id="email" name="email" class="form_input" placeholder=" " tabindex="1" required>
							<label for="email" class="form_label">Email</label>
						</div>
					</div>
				</div>

				<div class="buttons">
					<button class="next btn order-2 submit-next" type="submit" tabindex="2">Próximo</button>
					<button class="cancel btn order-1" type="button" tabindex="3">Cancelar</button>
				</div>
			</form>
		</main>
	</div>
</div>