<div class="container">
	<div class="content">
		<main id="forgotPassword" class="box col-md-6">
			<h1 class="title-forgot-password">Recuperação de conta</h1>

			<!-- <div class="road-circle-help">
				
			</div> -->

			<form action="?forgot_password=true" method="GET" class="form-row" id="formForgotPassword">
				<div class="form_div">
					<input type="email" name="email" id="email" class="form_input" placeholder=" ">
					<label for="email" class="form_label">Email</label>
				</div>
			</form>
		</main>
	</div>
</div>