<?php
	$actionLogo = 'action/logo.phtml';
	require_once($actionLogo);
?>

<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta name="keywords" content="HTML, CSS, JavaScript, PHP, MySql">
	<meta name="author" content="Carlos Alexandre">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta charset="utf-8">

	<!-- Bootstrap Css -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<!-- Font Awesome -->
	<script src="https://kit.fontawesome.com/90bfac5e12.js" crossorigin="anonymous"></script>

	<!-- Light Zoom CSS -->
	<link rel="stylesheet" href="/js/library/lightzoom-master/glassstyle.min.css">

	<!-- Fonts Google -->
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

	<!-- Estilo Css -->
	<link rel="stylesheet" href="/css/animation.css">
	<link rel="stylesheet" href="/css/estilo.css">
	<link rel="stylesheet" href="/css/media-query.css">
	<?php
		if (isset($this->view->css)) {
			foreach ($this->view->css as $indice => $estilo) {
				$fileStyle = '/css/'. $estilo .'.css';
				echo "<link rel='stylesheet' type='text/css' href='". $fileStyle ."'>";
			}
		}
	?>

	<title>Recibo - <?= isset($this->view->title) ? $this->view->title : 'Miniframework'; ?></title>
	<link rel="icon" href="/img/favicon.png">

	<!-- Jquery -->
	<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

	<!-- Bootstrap JS -->
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

	<!-- Light Zoom JS -->
	<script src="/js/library/lightzoom-master/lightzoom.js"></script>

</head>
<body>
	<?php
		if ($this->userLogado) {
			header('location: /dashboard');
		}
	?>

	<header class="container-fluid">
		<nav class="navbar navbar-expand-lg content-container">
			<?= logo() ?>

			<div class="navbar-toggler" id="hamburguer" type="button" data-toggle="collapse" data-target="#menu" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="hamburguer"></span>
	  		</div>

			<div id="menu" class="collapse navbar-collapse">
				<ul class="list-no menu-group ml-auto navbar-nav">
					<?php
						$itensMenu = [
							[
								"dir" => "/dashboard",
								"text" => "Dashboard",
							],
							[
								"dir" => "/modelos_recibo",
								"text" => "Modelos de Recibo",
								"title" => "Todos os modelos do recibo",
							]
						];

						$url = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
						foreach ($itensMenu as $item) {
				 			?>
							    <li class="item-menu">
									<a
										href="<?= $item['dir'] ?>"
										title="<?= $item['title'] ?? $item['text'] ?>"
										class="<?= $url == $item['dir'] ? 'active' : '' ?>"
									>
									<?= $item['text'] ?>
									</a>
								</li>
							<?php
						}
					?>
				</ul>

				<div class="button-auth mt-4 mt-lg-0">
					<a href="/cadastro" class="btn cadastro">Cadastrar-se</a>
					<a href="/login" class="btn login">Logar-se</a>
				</div>
			</div>
		</nav>
	</header>

	<?php
		$action = 'action/renderReportDefault.php';
		require_once($action);
	?>

	<?php
		$action = 'action/forgotPassword.php';
		require_once($action);
	?>

	<?= $this->content() ?>

	<?php
		$action = 'action/footer.phtml';
		require_once($action);
	?>

	<script src="/js/urlSocial.js"></script>
	<script src="/js/report.js"></script>
	<?php
		if (isset($this->view->js)) {
			foreach ($this->view->js as $indice => $script) {
				$fileScript = '/js/'. $script .'.js';
				echo "<script src='".$fileScript."'></script>";
			}
		}
	?>
</body>
</html>