<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta name="keywords" content="HTML, CSS, JavaScript, PHP, MySql">
	<meta name="author" content="Carlos Alexandre">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta charset="utf-8">

	<!-- Bootstrap Css -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<!-- Font Awesome -->
	<script src="https://kit.fontawesome.com/90bfac5e12.js" crossorigin="anonymous"></script>

	<!-- Estilo Css -->
	<link rel="stylesheet" href="/css/animation.css">
	<link rel="stylesheet" href="/css/estilo.css">
	<link rel="stylesheet" href="/css/media-query.css">
	<?php
		if (isset($this->view->css)) {
			foreach ($this->view->css as $indice => $estilo) {
				$fileStyle = '/css/'. $estilo .'.css';
				if (file_exists($fileStyle)) {
					echo "<link rel='stylesheet' type='text/css' href=' " . $fileStyle . " '>";
				}
			}
		}
	?>

	<title>Recibo - <?= isset($this->view->title) ? $this->view->title : 'Miniframework'; ?></title>
	<link rel="icon" href="">

	<!-- Jquery -->
	<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

	<!-- Bootstrap JS -->
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</head>
<body>
	<?php $valid = true; ?>

	<header>
		<nav class="navbar navbar-expand-md">
			<a href="/dashboard" class="brand">
				<i class="fas fa-receipt logo-receipt" title="Ícone recibo"></i>
				<h3 class="logo-text" title="Recibo online">Recibo Online</h3>
			</a>

			<div id="menu-user" class="order-md-1 mr-2 mr-md-0">
				<?php if ($valid) { ?>
					<div class="content-user" id="userContentHeader">
						<!-- <i class="fas fa-user-circle icon-user" title="Ícone do usuário"></i> -->
						<img src="/img/taylor.jpg" id="img-user">
						<i class="fas fa-sort-down icon-down"></i>
					</div>

					<div class="content-suport-user">
						<div class="menu-suport">
							<ul class="list-no" id="linksSuport">
								<li>
									<a href="/">
										<i class="fas fa-cog"></i>
										Minha Conta
									</a>
								</li>
								<li>
									<a href="/">
										<i class="fas fa-star"></i>
										Meus Favoritos
									</a>
								</li>
								<li>
									<a href="/">
										<i class="fas fa-archive"></i>
										Minha Coleção
									</a>
								</li>
								<li>
									<a href="/">
										<i class="fas fa-sliders-h"></i>
										Configurações
									</a>
								</li>
								<li>
									<a href="/">
										<i class="fas fa-trophy"></i>
										Adquirir o Premiew
									</a>
								</li>
							</ul>
						</div>
					</div>
				<?php } else { ?>
					<a href="/cadastro" class="btn cadastro">Cadastrar-se</a>
					<a href="/login" class="btn login">Logar-se</a>
				<?php } ?>
			</div>

			<div class="navbar-toggler" id="hamburguer" type="button" data-toggle="collapse" data-target="#menu" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="hamburguer"></span>
	  		</div>

			<div id="menu" class="collapse navbar-collapse">
				<ul class="list-no menu-group ml-auto navbar-nav">
					<?php
						$itensMenu = [
							[
								"dir" => "/dashboard",
								"text" => "Dashboard",
							],
							[
								"dir" => "/modelos_recibo",
								"text" => "Modelos de Recibo",
								"title" => "Todos os modelos do recibo",
							],
							[
								"dir" => "/recibos",
								"text" => "Últimos Recibos",
								"login" => true,
							],
						];

						$url = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
						foreach ($itensMenu as $item) {
							if ($valid || !isset($item['login'])) {
				 			?>
							    <li class="item-menu">
									<a
										href="<?= $item['dir'] ?>"
										title="<?= $item['title'] ?? $item['text'] ?>"
										class="<?= $url == $item['dir'] ? 'active' : '' ?>"
									>
									<?= $item['text'] ?>
									</a>
								</li>
							<?php }
						}
					?>
				</ul>
			</div>
		</nav>
	</header>

	<?= $this->content() ?>

	<script src="/js/script.js"></script>
	<?php
		if (isset($this->view->js)) {
			foreach ($this->view->js as $indice => $script) {
				$fileScript = '/js/'. $script .'.js';
				if (file_exists($fileScript)) {
					echo "<script src=' " .$fileScript. " '></script>";
				}
			}
		}
	?>
</body>
</html>